### ISSUE TITLE
[Tree widget] More than one header button results in first button not showing up in dropdown

### ISSUE THREAD

**Issue by ChrisBAtBentley** [iTwin/viewer-components-react#1105]
When using a ModelsTreeComponent or CategoriesTreeComponent that has more than one headerButton in the props (such as the default when the prop is not used), and then clicking the search bar for the component, the first button will not appear in the dropdown. If there is only one button, the button stays the same during the search bar being active. The issue appears to come from the HeaderButtons method/element in TreeHeader.tsx.

**Comment by aruniverse** [comment]
Not entirely sure what is being said here. Please attach screenshots and more details of whatever issue you are facing

**Comment by grigasp** [comment]
Also, please specify the version of `@itwin/tree-widget-react` & `@itwin/itwinui-react` that you're using.

**Comment by ChrisBAtBentley** [comment]
We are currently on 3.0.1 on @itwin/tree-widget-react and 3.15.4 on @itwin/itwinui-react. I've included some photos of the issue. When the search bar is not active, all buttons show up fine. However, when the search bar is activated, the dropdown menu only shows 5 of the 6 buttons.
![Image](https://github.com/user-attachments/assets/05c660af-5514-4175-9dac-499c744cb536)
![Image](https://github.com/user-attachments/assets/6e34aae2-6b91-47fc-9673-810806e0b834)

**Comment by grigasp** [comment]
I can't reproduce this in our test viewer and our e2e tests suggest it's working fine: https://github.com/iTwin/viewer-components-react/blob/master/packages/itwin/tree-widget/src/e2e-tests/ModelsTree.test.ts-snapshots/Models-tree-Density-default-header-buttons-overflow-1-chromium-linux.png. 

Could you please try to set up a sandbox or something that we could use to reproduce it?

**Comment by ChrisBAtBentley** [comment]
Sorry for the late response; I will need to look into getting a separate sandbox set up. I am not sure what the browser the issue was reported in was but I can replicate it in Edge

**Comment by grigasp** [comment]
I'm getting `0` there. The `@itwin/itwinui-react` package received [an overhaul for overflow handling](https://github.com/iTwin/iTwinUI/pull/2154) in version `3.16.0` - can you see if it helps?

**Comment by ChrisBAtBentley** [comment]
That seemed to do the trick! Thank you!

**Comment by jason-crow** [comment]
@aruniverse @grigasp this issue turns out to be unrelated to itwinui-react@3.15.x, in fact, the issue was that our tree-widget-react@3.x was using itwinui-react@2.x instead of 3.x

this happens because as we still have both itwinui-react v2 and v3 in our app and we set v3 as an alias dependency, when a transitive dep like tree-widget-react asks for a peer on itwinui-react it gets paired to the v2 version

this has been an ongoing issue since we know that itwinui-react should be a peer since it contains the ThemeProvider singleton but have no way to seemingly make it match with the v3 version (and if we flip the alias to v2 the inverse happens).

We do have a workaround though, which is to add some logic in the pnpmfile.cjs to remove the peer on itwinui-react and instead set it as a dependency for a set of packages we know we want to do this for. Doing this ensures the right version is used and we  also have a pnpm override to ensure only 1 version of itwinui-react v3 exists to prevent setting it as a dep instead of a peer from leading to multiple versions that would break the ThemeProvider use. T

This workaround simply wasn't yet matching to tree-widget-react because in v2 it sets itwinui-react as a dep instead of a peer and we didn't consider this when we first added v3. After updating the workaround to properly mend tree-widget-react this issue is no longer reproducible

btw the plan is (and we are nearly in a position to do this) to get all our deps to use v3 only then remove the alias make our app just install itwinui-react v3 and remove this pnpmfile.cjs workaround, but until then its worked well enough so long as we keep up with it

Sorry for not discovering this sooner and wasting your time!
