### ISSUE TITLE
[tree-widget] Documentation for `tree-widget` custom trees outdated

### ISSUE THREAD

**Issue by anmolshres98** [iTwin/viewer-components-react#1114]
The documentation here: https://github.com/iTwin/viewer-components-react/tree/master/packages/itwin/tree-widget#custom-trees has code snippets which are erroneous.

Given this breaking change: https://github.com/iTwin/presentation/blob/e0d3176a099cd345b82f089fec63d8eddb0327d8/packages/hierarchies/CHANGELOG.md?plain=1#L136C3-L140C1, if someone is using latest version of `@itwin/presentation-hierarchies`, the would face an error.

The docs should be updated to reflect the change in api

**Comment by grigasp** [comment]
Thanks for reporting this, @anmolshres98. Our readmes use snippets that are taken from a compiled and run tests, so I was a bit surprised to see this issue. Turns out we're missing the "check" script in our pipelines, so nobody was reminded to update the markdowns after updating the tests... Will fix this asap.
