### ISSUE TITLE
Releasing a new package version doesn't update changelog

### ISSUE THREAD

**Issue by grigasp** [iTwin/viewer-components-react#601]
We released `@itwin/property-grid-react@1.0.1`, but [the changelog was not updated](https://github.com/iTwin/viewer-components-react/blob/master/packages/itwin/property-grid/CHANGELOG.md) and [the changefile is still there](https://github.com/iTwin/viewer-components-react/blob/master/common/changes/%40itwin/property-grid-react/property_grid_selected_elements_button_2023-08-02-08-34.json). Need to figure out why and fix it.

**Comment by saskliutas** [comment]
This is happening because [`CHANGELOG.json`](https://github.com/iTwin/viewer-components-react/blob/226f1e40b13e22546016d6c08b7e8062bac0a7d8/packages/itwin/property-grid/CHANGELOG.json#L687) file for property-grid-react package already has an entry for 1.0.1 version. When bumping version rush does not create new changelog entries based on change files if `CHANGELOG.json` contains entry for bumped version already. https://github.com/microsoft/rushstack/blob/5c8c336725122fada147ee57f381e3ac8570b4f7/libraries/rush-lib/src/logic/ChangelogGenerator.ts#L106

It looks like `tree-widget-react` package also have some old entries in `CHANGELOG.json` file from before it was renamed and we will have same problem releasing minor and path 1.x versions.

One solution for this would be to remove old entries from `CHANGELOG.json` and regenerate `CHANGELOG.md` file.

**Comment by grigasp** [comment]
> One solution for this would be to remove old entries from `CHANGELOG.json` and regenerate `CHANGELOG.md` file.

Agree, I think we need to remove all entries from when the package was in `@bentley` scope. Also, while at it, I think we should fix the changelog messages for pre-0.7.0 versions - there are a number of messages starting with lower case, using poor formating, etc.

@aruniverse what do you think about "changing the history"? 😄

**Comment by aruniverse** [comment]
> @aruniverse what do you think about "changing the history"? 😄

I'm good with that; I guess we'll need to update all the pkgs whose version was reset to 0.x after switching to the itwin scope not just property grid. 

Thx for reporting this!
