### ISSUE TITLE
PropertyGrid: Cannot get persisted user preference showNullValues because 'IModelApp.userPreferences' not defined. 

### ISSUE THREAD

**Issue by jutian88** [iTwin/viewer-components-react#781]
### Describe the bug

![image](https://github.com/iTwin/appui/assets/30802089/aa5da121-f6e4-4721-80a2-5862c48a13e3)

hi here!
I added PropertyGrid components and initialized the Presentation, but error were reported in the image.

```[tasklist]
### Tasks
```

**Comment by jutian88** [comment]
Thank you for your reply. I introduced them in order without considering persistence, but prooertyGrid reported the above error and the prooertyGrid component could not be displayed. I hope the component can be displayed. How to implement it in the code?

**Comment by grigasp** [comment]
> ... and the prooertyGrid component could not be displayed. I hope the component can be displayed. How to implement it in the code? https://www.npmjs.com/package/@itwin/property-grid-react

Sorry, from your initial comment I didn't realize the component wasn't working. Generally, the component is added to iTwin.js apps using `UiItemsProvider` - you can see how that's done [here](https://github.com/iTwin/viewer-components-react/blob/3dfed20b3f7f63c6173227d1e5ab5084a41f55cc/apps/test-viewer/src/UiProvidersConfig.tsx#L112-L123). 

Please also note that the property grid only shows up when you select some element.

**Comment by jutian88** [comment]
In fact, I've done this but PropertyGrid doesn't work
![image](https://github.com/iTwin/viewer-components-react/assets/30802089/f20c4293-0701-4fe4-9251-e02d2ca75ba8)
![image](https://github.com/iTwin/viewer-components-react/assets/30802089/59f5b22e-17b3-442b-9251-9dc846332cc5)

**Comment by jutian88** [comment]
![image](https://github.com/iTwin/viewer-components-react/assets/30802089/6d9b0b15-4816-41b5-9371-cacdfbce2772)
I have also selected some element.

**Comment by grigasp** [comment]
What you have looks okay. Could you push your code to some public repo where I could have a look at it?

**Comment by jutian88** [comment]
@grigasp 
thanks~

https://github.com/jutian88/appui

**Comment by grigasp** [comment]
Thanks. I didn't realize you were using `appui-test-app`. The problem is that selection change doesn't get to the property widget.

The property widget uses [unified selection](https://www.itwinjs.org/presentation/unified-selection/) system to find out about what's selected. The system comes with `@itwin/presentation-frontend` package and the components that interact with selection need to hook into it. The property widget uses Presentation library by default and hooks into unified selection automatically. However, none of the appui packages know about Presentation library or unified selection, so the graphics view component doesn't work with the system. To achieve that, you need do use a viewport component like [this](https://github.com/iTwin/viewer/blob/master/packages/modules/viewer-react/src/components/app-ui/providers/UnifiedSelectionViewportControl.tsx).

I suggest looking at [@itwin/cra-template-web-viewer](https://www.npmjs.com/package/@itwin/cra-template-web-viewer) as a starter app. Adding @aruniverse who, I believe, can consult if needed.

**Comment by jutian88** [comment]
I will take your suggestion and try to do.
Best wishes to you

**Comment by jutian88** [comment]
it works!!
![image](https://github.com/iTwin/viewer-components-react/assets/30802089/ca51c094-5180-4add-8445-f219d283155f)

I show the changes in the picture:
![image](https://github.com/iTwin/viewer-components-react/assets/30802089/bd31eaf5-dfde-4392-b118-76939c65c69a)
![image](https://github.com/iTwin/viewer-components-react/assets/30802089/7da5e6fe-8cf0-407b-b635-a6542815730e)
