### ISSUE TITLE
Tree widget: Filtering dialog takes very long to load in specific case

### ISSUE THREAD

**Issue by grigasp** [iTwin/viewer-components-react#914]
http://localhost:3000/?iTwinId=523a1365-2c85-4383-9e4c-f9ec25d0e107&iModelId=e8279804-0a39-4c7c-9a3f-361baa676e8b

Took ~24 seconds to load. DevTools show that network requests took only ~7 seconds.

https://bentley.sharepoint.com/:v:/s/Rules-DrivenPresentation/EZBRN8fRbq5MlfkMAfnDuHQB4u1etE7aetBqAkr7FhtrZw?e=y1MKwe

**Comment by Yato333** [comment]
- As soon as the dialog is opened, all category elements are queried (~300,000) so that a Descriptor can be created.
- Significant amount of time is spent deserializing the query results and collecting them to a `KeySet`.
- Having DevTools opened and `React.StrictMode` greatly exacerbates the performance. (Strict Mode causes to run all queries twice)

Average measured performance:
-- | Query of Category instances + collection to KeySet | Presentation.getContentDescriptor
-- | -- | --
StrictMode + DevTools opened | 26 sec | 750-900 ms
StrictMode + DevTools closed | 6.6 sec | Same
StrictMode off + DevTools opened | 16 sec | Same
StrictMode off + DevTools closed | 4.5 sec | Same

Profile results with StrictMode off + DevTools closed:
![Screenshot 2024-06-19 162348](https://github.com/iTwin/viewer-components-react/assets/29233962/862c4fc3-bfb6-4e08-9384-de772c2bea2e)
